name: Check Linting, Run Tests, and Generate Code Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install depedencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest pytest-cov
     
    # - name: Run ruff
    #   run: |
    #     ruff check src/ tests/ --config pyproject.toml
    
    - name: Run pytest with coverage
      run: pytest --cov-report=html # outputs coverage report to htmlcov
    
    - name: Upload coverage report as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: htmlcov